### PR TITLE
Added Hindi language class

### PR DESCRIPTION
**Pull request by bismitpanda**

### CODE REVIEW

**Comment by t3l3machus** [comment]
Thank you!!

**Comment by t3l3machus** [comment]
@blood-rogue can you run some tests? I am not sure it transliterates "correctly"

**Comment by bismitpanda** [comment]
As far I have tried it produced correctly and my test dataset was small as I used some common Hindi names. Can you please provide test data set so that I can check?

**Comment by t3l3machus** [comment]
I got some random names from google, tbh I don't know what to expect as a correct transliteration result, I just compared it to google translate. I tried this for example, it transliterates weird  -> कनहयलल मश 
Can you provide some common Hindi names and how they are supposed to be written using the Latin alphabet? just to check out how it's doing and have a sample.

**Comment by bismitpanda** [comment]
There are some letters which are giving issues (I used a 1000 names dataset now), I will make another PR with the corrections. Thanks for bringing this to notice.

**Comment by bismitpanda** [comment]
The `langdetect` library is detecting different languages like Marathi and Nepali instead of Hindi. So the some names are being omitted. And I have made a new PR.

**Pull request merged**
